spring:
  application:
    name: guilds-ai
  threads:
    virtual:
      enabled: true
  ai:
    openai:
      chat:
        options:
          model: gpt-4o-mini
          functions:
            - LessonSlotsNearCity
            - CurrentDateTime
      embedding:
        options:
          model: text-embedding-3-small